# Generated by Django 2.2.19 on 2021-04-26 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
            options={
                'verbose_name': 'CRA Rate',
            },
        ),
        migrations.CreateModel(
            name='FtbRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('ftb_supplement', models.DecimalField(decimal_places=2, max_digits=9)),
                ('income_free_area', models.DecimalField(decimal_places=2, max_digits=9)),
                ('maximum_income', models.DecimalField(decimal_places=2, max_digits=9)),
                ('additional_income_per_child', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ftb_a_base_rate_payments', models.DecimalField(decimal_places=2, max_digits=9)),
                ('large_family_supplement', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'FTB Rate',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceIncomeTestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentAssessmentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ftb', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('maintenance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('cra', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('active', models.CharField(blank=True, choices=[('Yes', 'Yes')], max_length=10, null=True, unique=True, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTypeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maintenance_income_test_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrelink.MaintenanceIncomeTestRate')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.MaintenanceType')),
            ],
        ),
        migrations.CreateModel(
            name='FtbAMaximumPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dependant_child_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Relationship')),
                ('ftb_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrelink.FtbRate')),
            ],
            options={
                'verbose_name': 'FTB-A Maximum Payment',
            },
        ),
        migrations.CreateModel(
            name='FamilySituationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_cra_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lower_threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('upper_thershold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cra_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrelink.CraRate')),
                ('family_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.FamilySituation')),
            ],
        ),
    ]
