# Generated by Django 2.2.19 on 2021-04-26 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50)),
                ('transaction_chp_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_rent_effective_date', models.DateField(blank=True, null=True)),
                ('transaction_income_period', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly')], max_length=11, null=True)),
                ('transaction_property_market_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Weekly', max_digits=7, null=True)),
                ('transaction_number_of_family_group', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('transaction_cruser', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_prop_id', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_state', models.CharField(blank=True, max_length=50, null=True)),
                ('family_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('family_group_family_type', models.CharField(blank=True, max_length=50, null=True)),
                ('family_group_last_rent', models.DecimalField(blank=True, decimal_places=2, help_text='per week', max_digits=7, null=True)),
                ('family_group_any_income_support_payment', models.BooleanField(blank=True, null=True)),
                ('family_group_cra_eligibilty', models.BooleanField(blank=True, help_text='legislated', null=True)),
                ('family_group_cra_amount', models.DecimalField(blank=True, decimal_places=2, help_text='per week', max_digits=6, null=True)),
                ('family_group_ftb_a', models.DecimalField(blank=True, decimal_places=2, help_text='Legislated - per week', max_digits=6, null=True, verbose_name='FTB-A')),
                ('family_group_ftb_b', models.DecimalField(blank=True, decimal_places=2, help_text='Legislated - per week', max_digits=6, null=True, verbose_name='FTB-B')),
                ('family_group_maintenance_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Per year', max_digits=7, null=True)),
                ('family_group_maintenance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('family_group_number_of_additional_children', models.IntegerField(blank=True, null=True)),
                ('family_member_name', models.CharField(blank=True, max_length=100, null=True)),
                ('family_member_contact_id', models.PositiveIntegerField(blank=True, null=True)),
                ('family_member_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('family_member_partnered', models.BooleanField(blank=True, null=True)),
                ('family_member_date_of_birth', models.DateField(blank=True, null=True)),
                ('family_member_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('family_member_care_percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('family_member_income', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('family_member_rent_percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Import',
            },
        ),
    ]
