# Generated by Django 2.2.19 on 2021-04-26 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FG_1', 'FG_1'), ('FG_2', 'FG_2'), ('FG_3', 'FG_3'), ('FG_4', 'FG_4'), ('FG_5', 'FG_5')], max_length=10)),
                ('last_rent', models.DecimalField(blank=True, decimal_places=2, help_text='per week', max_digits=7, null=True)),
                ('any_income_support_payment', models.BooleanField(blank=True, null=True)),
                ('cra_eligibilty', models.BooleanField(blank=True, help_text='legislated', null=True)),
                ('cra_amount', models.DecimalField(blank=True, decimal_places=2, help_text='per week', max_digits=6, null=True)),
                ('ftb_a', models.DecimalField(blank=True, decimal_places=2, help_text='Legislated - per week', max_digits=6, null=True, verbose_name='FTB-A')),
                ('ftb_b', models.DecimalField(blank=True, decimal_places=2, help_text='Legislated - per week', max_digits=6, null=True, verbose_name='FTB-B')),
                ('maintenance_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Per year', max_digits=7, null=True)),
                ('number_of_additional_children', models.IntegerField(blank=True, null=True)),
                ('number_of_family_member', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)])),
                ('family_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.FamilySituation')),
                ('maintenance_type', models.ForeignKey(blank=True, limit_choices_to={'name__in': ['Single', 'Couple']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.MaintenanceType')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chp_reference', models.CharField(max_length=50, unique=True)),
                ('rent_effective_date', models.DateField(blank=True, null=True)),
                ('income_period', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly')], default='Weekly', max_length=11, null=True)),
                ('property_market_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Weekly', max_digits=7, null=True)),
                ('number_of_family_group', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('cruser', models.CharField(blank=True, max_length=50, null=True)),
                ('prop_id', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('partnered', models.BooleanField(blank=True, null=True)),
                ('care_percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('income', models.DecimalField(blank=True, decimal_places=2, help_text='Excluding:\n1. Maintenance\n2. FTB-A & FTB-B\n3. CRA\nbut incl. ES(1) for all payments and FTB-A & FTB-B', max_digits=6, null=True)),
                ('rent_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='calculator.FamilyGroup')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Relationship')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fmember', to='calculator.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='familygroup',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_groups', to='calculator.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='familygroup',
            unique_together={('transaction', 'name')},
        ),
    ]
